In [1]:
# start with output of notebook 2 from
# https://github.com/mmayers12/semmed/tree/master/nbs
# nodes.csv and edges.csv

In [2]:
# convert the pmids columns from a set of strings to a single semicolon delimited string
# change the neg to the same prop without neg and add a neg column
# make every edge uni-directional and remove ">"
# make columns for domain pred range

In [2]:
import os
import pickle
%matplotlib inline
import pandas as pd
import re
import seaborn as sns
from tqdm import tqdm

In [4]:
def sanitize(x):
    """Some pmids have the appearance of '2015332 [3]' for some reason. This fixes that"""
    if type(x) == str:
        if ' ' in x:
            x = x.split(' ')[0]
    return x

In [5]:
x = !wc -l edges.csv
wc = int(x[0].split(" ")[0])

In [17]:
# can't load into ram. too big. It doesn't like pmid column. do in chunks
# convert the pmids columns from a set of string to a single semicolon delimited string
edges = pd.read_csv('edges.csv', converters={'pmids':eval}, chunksize=100000)
df = pd.read_csv('edges.csv', nrows=0)
df.rename(columns={':START_ID': 'START_ID', ':END_ID': 'END_ID', ':TYPE': 'TYPE'}, inplace=True)
# write out column headers
df.to_csv("edges_pmid.csv", index=0)
for df in tqdm(edges, total=wc/100000):
    df['pmids'] = df['pmids'].apply(lambda ids: set([str(sanitize(x)) for x in ids]))
    df['pmids'] = df['pmids'].apply(lambda x:";".join(x))
    df.to_csv("edges_pmid.csv", mode='a', header=False, index=0)

  0%|          | 0/103.100565 [00:00<?, ?it/s]


  1%|          | 1/103.100565 [00:04<07:31,  4.42s/it]

  2%|▏         | 2/103.100565 [00:07<06:08,  3.64s/it]

  3%|▎         | 3/103.100565 [00:09<05:30,  3.30s/it]

  4%|▍         | 4/103.100565 [00:12<05:20,  3.23s/it]

  5%|▍         | 5/103.100565 [00:15<05:11,  3.18s/it]

  6%|▌         | 6/103.100565 [00:18<05:04,  3.14s/it]

  7%|▋         | 7/103.100565 [00:21<04:57,  3.09s/it]

  8%|▊         | 8/103.100565 [00:24<04:51,  3.07s/it]

  9%|▊         | 9/103.100565 [00:27<04:47,  3.06s/it]

 10%|▉         | 10/103.100565 [00:30<04:46,  3.07s/it]

 11%|█         | 11/103.100565 [00:33<04:44,  3.09s/it]

 12%|█▏        | 12/103.100565 [00:37<04:40,  3.08s/it]

 13%|█▎        | 13/103.100565 [00:40<04:37,  3.08s/it]

 14%|█▎        | 14/103.100565 [00:43<04:33,  3.07s/it]

 15%|█▍        | 15/103.100565 [00:45<04:28,  3.05s/it]

 16%|█▌        | 16/103.100565 [00:48<04:25,  3.04s/it]

 16%|█▋        | 17/103.100565 [00:51<04:20,  3.02s/it]

 17%|█▋        | 18/103.100565 [00:54<04:17,  3.02s/it]

 18%|█▊        | 19/103.100565 [00:57<04:13,  3.01s/it]

 19%|█▉        | 20/103.100565 [01:00<04:10,  3.01s/it]

 20%|██        | 21/103.100565 [01:03<04:08,  3.03s/it]

 21%|██▏       | 22/103.100565 [01:06<04:04,  3.01s/it]

 22%|██▏       | 23/103.100565 [01:09<04:01,  3.01s/it]

 23%|██▎       | 24/103.100565 [01:12<03:57,  3.00s/it]

 24%|██▍       | 25/103.100565 [01:14<03:53,  2.99s/it]

 25%|██▌       | 26/103.100565 [01:17<03:51,  3.00s/it]

 26%|██▌       | 27/103.100565 [01:20<03:47,  2.99s/it]

 27%|██▋       | 28/103.100565 [01:23<03:44,  3.00s/it]

 28%|██▊       | 29/103.100565 [01:27<03:42,  3.00s/it]

 29%|██▉       | 30/103.100565 [01:30<03:40,  3.01s/it]

 30%|███       | 31/103.100565 [01:33<03:37,  3.02s/it]

 31%|███       | 32/103.100565 [01:36<03:33,  3.01s/it]

 32%|███▏      | 33/103.100565 [01:38<03:30,  3.00s/it]

 33%|███▎      | 34/103.100565 [01:41<03:26,  2.99s/it]

 34%|███▍      | 35/103.100565 [01:44<03:23,  2.99s/it]

 35%|███▍      | 36/103.100565 [01:47<03:19,  2.98s/it]

 36%|███▌      | 37/103.100565 [01:49<03:16,  2.97s/it]

 37%|███▋      | 38/103.100565 [01:52<03:13,  2.97s/it]

 38%|███▊      | 39/103.100565 [01:55<03:10,  2.97s/it]

 39%|███▉      | 40/103.100565 [01:58<03:07,  2.97s/it]

 40%|███▉      | 41/103.100565 [02:01<03:03,  2.96s/it]

 41%|████      | 42/103.100565 [02:04<03:00,  2.96s/it]

 42%|████▏     | 43/103.100565 [02:07<02:57,  2.95s/it]

 43%|████▎     | 44/103.100565 [02:09<02:54,  2.95s/it]

 44%|████▎     | 45/103.100565 [02:12<02:51,  2.95s/it]

 45%|████▍     | 46/103.100565 [02:17<02:50,  2.98s/it]

 46%|████▌     | 47/103.100565 [02:24<02:52,  3.08s/it]

 47%|████▋     | 48/103.100565 [02:31<02:53,  3.15s/it]

 48%|████▊     | 49/103.100565 [02:34<02:51,  3.16s/it]

 48%|████▊     | 50/103.100565 [02:38<02:48,  3.18s/it]

 49%|████▉     | 51/103.100565 [02:42<02:46,  3.19s/it]

 50%|█████     | 52/103.100565 [02:46<02:43,  3.20s/it]

 51%|█████▏    | 53/103.100565 [02:51<02:42,  3.24s/it]

 52%|█████▏    | 54/103.100565 [02:55<02:39,  3.26s/it]

 53%|█████▎    | 55/103.100565 [03:00<02:37,  3.28s/it]

 54%|█████▍    | 56/103.100565 [03:03<02:34,  3.28s/it]

 55%|█████▌    | 57/103.100565 [03:07<02:31,  3.28s/it]

 56%|█████▋    | 58/103.100565 [03:10<02:28,  3.29s/it]

 57%|█████▋    | 59/103.100565 [03:14<02:25,  3.29s/it]

 58%|█████▊    | 60/103.100565 [03:17<02:22,  3.30s/it]

 59%|█████▉    | 61/103.100565 [03:21<02:18,  3.30s/it]

 60%|██████    | 62/103.100565 [03:25<02:15,  3.31s/it]

 61%|██████    | 63/103.100565 [03:28<02:12,  3.31s/it]

 62%|██████▏   | 64/103.100565 [03:30<02:08,  3.29s/it]

 63%|██████▎   | 65/103.100565 [03:33<02:05,  3.28s/it]

 64%|██████▍   | 66/103.100565 [03:35<02:01,  3.27s/it]

 65%|██████▍   | 67/103.100565 [03:39<01:58,  3.28s/it]

 66%|██████▌   | 68/103.100565 [03:45<01:56,  3.32s/it]

 67%|██████▋   | 69/103.100565 [03:52<01:54,  3.37s/it]

 68%|██████▊   | 70/103.100565 [03:56<01:51,  3.38s/it]

 69%|██████▉   | 71/103.100565 [03:59<01:48,  3.38s/it]

 70%|██████▉   | 72/103.100565 [04:03<01:45,  3.38s/it]

 71%|███████   | 73/103.100565 [04:08<01:42,  3.40s/it]

 72%|███████▏  | 74/103.100565 [04:11<01:38,  3.40s/it]

 73%|███████▎  | 75/103.100565 [04:15<01:35,  3.40s/it]

 74%|███████▎  | 76/103.100565 [04:18<01:32,  3.40s/it]

 75%|███████▍  | 77/103.100565 [04:21<01:28,  3.39s/it]

 76%|███████▌  | 78/103.100565 [04:24<01:25,  3.39s/it]

 77%|███████▋  | 79/103.100565 [04:33<01:23,  3.46s/it]

 78%|███████▊  | 80/103.100565 [04:42<01:21,  3.53s/it]

 79%|███████▊  | 81/103.100565 [04:53<01:19,  3.62s/it]

 80%|███████▉  | 82/103.100565 [04:58<01:16,  3.64s/it]

 81%|████████  | 83/103.100565 [05:02<01:13,  3.64s/it]

 81%|████████▏ | 84/103.100565 [05:05<01:09,  3.63s/it]

 82%|████████▏ | 85/103.100565 [05:07<01:05,  3.62s/it]

 83%|████████▎ | 86/103.100565 [05:10<01:01,  3.61s/it]

 84%|████████▍ | 87/103.100565 [05:13<00:58,  3.60s/it]

 85%|████████▌ | 88/103.100565 [05:16<00:54,  3.60s/it]

 86%|████████▋ | 89/103.100565 [05:19<00:50,  3.59s/it]

 87%|████████▋ | 90/103.100565 [05:22<00:46,  3.58s/it]

 88%|████████▊ | 91/103.100565 [05:25<00:43,  3.58s/it]

 89%|████████▉ | 92/103.100565 [05:29<00:39,  3.58s/it]

 90%|█████████ | 93/103.100565 [05:33<00:36,  3.59s/it]

 91%|█████████ | 94/103.100565 [05:37<00:32,  3.59s/it]

 92%|█████████▏| 95/103.100565 [05:42<00:29,  3.60s/it]

 93%|█████████▎| 96/103.100565 [05:46<00:25,  3.61s/it]

 94%|█████████▍| 97/103.100565 [05:53<00:22,  3.64s/it]

 95%|█████████▌| 98/103.100565 [05:57<00:18,  3.65s/it]

 96%|█████████▌| 99/103.100565 [06:02<00:15,  3.66s/it]

 97%|█████████▋| 100/103.100565 [06:07<00:11,  3.67s/it]

 98%|█████████▊| 101/103.100565 [06:10<00:07,  3.67s/it]

 99%|█████████▉| 102/103.100565 [06:13<00:04,  3.66s/it]

100%|█████████▉| 103/103.100565 [06:16<00:00,  3.65s/it]

104it [06:16,  3.62s/it]

In [4]:
# now we can load the whole thing
edges = pd.read_csv("edges_pmid.csv")
edges.head()

,START_ID,END_ID,TYPE,pmids,n_pmids
0,C1273870,C0282623,ADMINISTERED_TO_ABatAB,17170614,1
1,C0935546,C0221192,ADMINISTERED_TO_ABatCI,15856663,1
2,C1273870,C1138603,ADMINISTERED_TO_ABatCI,12943031;15842188,2
3,C1273870,C0221192,ADMINISTERED_TO_ABatCI,25503364;22250100;24417454;16723949;19337198;2...,53
4,C0556656,C0221192,ADMINISTERED_TO_ABatCI,17684606;16230038;17323301;14707659;17530066;1...,7

In [5]:
# change the neg to the same prop without neg and add a neg column
idx = edges["TYPE"].str.startswith("NEG_")
edges['NEG'] = False
edges.loc[idx, 'NEG'] = True
edges.loc[idx, 'TYPE'] = edges[idx].TYPE.str.replace("NEG_", "")
edges[edges.NEG].head()

,START_ID,END_ID,TYPE,pmids,n_pmids,NEG
12500123,C0036592,C0027361,ADMINISTERED_TO_ABnatLB,24526037,1,True
12500124,C1273870,C0043210,ADMINISTERED_TO_ABnatLB,21627742;9576289;9824792;16864466,4,True
12500125,C0441648,C0679646,ADMINISTERED_TO_ABnatLB,25314278,1,True
12500126,C1273870,C0334885,ADMINISTERED_TO_ABnatLB,24214789,1,True
12500127,C0035028,C0030705,ADMINISTERED_TO_ABnatLB,20562622,1,True

In [6]:
# make every edge uni-directional and remove ">"
edges.TYPE = edges.TYPE.str.replace(">", "")

In [7]:
# get columns for domain, pred, range
rec = re.compile(r'([a-z]+)')
split_dr = lambda x: re.split(rec, x.rsplit("_", 1)[1])
print(split_dr("ADMINISTERED_TO_ABatAB"))
der = edges.TYPE.apply(split_dr)
der_df = pd.DataFrame(der.tolist(), columns=['domain', 'pred', 'range'])
edges['DOMAIN'] = der_df.domain
edges['PRED'] = der_df.pred
edges['RANGE'] = der_df.range

['AB', 'at', 'AB']

In [10]:
edges[edges.NEG].head()

,START_ID,END_ID,TYPE,pmids,n_pmids,NEG,DOMAIN,PRED,RANGE
12500123,C0036592,C0027361,ADMINISTERED_TO_ABnatLB,24526037,1,True,AB,nat,LB
12500124,C1273870,C0043210,ADMINISTERED_TO_ABnatLB,21627742;9576289;9824792;16864466,4,True,AB,nat,LB
12500125,C0441648,C0679646,ADMINISTERED_TO_ABnatLB,25314278,1,True,AB,nat,LB
12500126,C1273870,C0334885,ADMINISTERED_TO_ABnatLB,24214789,1,True,AB,nat,LB
12500127,C0035028,C0030705,ADMINISTERED_TO_ABnatLB,20562622,1,True,AB,nat,LB

In [11]:
# fix the pred abv for negative edges
edges.loc[edges.NEG, 'PRED'] = edges.loc[edges.NEG, 'PRED'].apply(lambda x:x[1:])

In [13]:
edges[edges.NEG].head()

,START_ID,END_ID,TYPE,pmids,n_pmids,NEG,DOMAIN,PRED,RANGE
12500123,C0036592,C0027361,ADMINISTERED_TO_ABnatLB,24526037,1,True,AB,at,LB
12500124,C1273870,C0043210,ADMINISTERED_TO_ABnatLB,21627742;9576289;9824792;16864466,4,True,AB,at,LB
12500125,C0441648,C0679646,ADMINISTERED_TO_ABnatLB,25314278,1,True,AB,at,LB
12500126,C1273870,C0334885,ADMINISTERED_TO_ABnatLB,24214789,1,True,AB,at,LB
12500127,C0035028,C0030705,ADMINISTERED_TO_ABnatLB,20562622,1,True,AB,at,LB

In [16]:
# recreate the type column
edges['TYPE'] = edges.DOMAIN + edges.PRED + edges.RANGE

In [17]:
edges[edges.NEG].head()

,START_ID,END_ID,TYPE,pmids,n_pmids,NEG,DOMAIN,PRED,RANGE
12500123,C0036592,C0027361,ABatLB,24526037,1,True,AB,at,LB
12500124,C1273870,C0043210,ABatLB,21627742;9576289;9824792;16864466,4,True,AB,at,LB
12500125,C0441648,C0679646,ABatLB,25314278,1,True,AB,at,LB
12500126,C1273870,C0334885,ABatLB,24214789,1,True,AB,at,LB
12500127,C0035028,C0030705,ABatLB,20562622,1,True,AB,at,LB

In [22]:
# edges['PRED_FULL'] = edges.TYPE.map(lambda x:x.rsplit("_",1)[0])

In [18]:
# dump back out
edges.to_csv("edges_sanitized.csv", index=None)

In [4]:
# rename nodes columns
nodes = pd.read_csv('nodes.csv')
nodes = nodes.rename(columns={':ID': 'ID', ':LABEL': 'TYPE', 'name': 'label'})
nodes.to_csv("nodes_sanitized.csv", index=None)

In [26]:
# save abbreviations
type_abv = {
 'Activities & Behaviors': 'AB',
 'Anatomy': 'A',
 'Compound': 'C',
 'Chemicals & Drugs': 'CD',
 'Concepts & Ideas': 'CI',
 'Devices': 'DV',
 'Disease': 'D',
 'Disorders': 'DO',
 'Genes & Molecular Sequences': 'G',
 'Geographic Areas': 'GA',
 'Living Beings': 'LB',
 'Objects': 'OB',
 'Occupations': 'OC',
 'Organizations': 'OR',
 'Phenomena': 'PH',
 'Physiology': 'PS',
 'Procedures': 'PR'
}
abv_type = {v:k for k,v in type_abv.items()}

In [27]:
pred_abr = {
 'ADMINISTERED_TO': 'at',
 'AFFECTS': 'af',
 'ASSOCIATED_WITH': 'aw',
 'AUGMENTS': 'ag',
 'CAUSES': 'c',
 'COEXISTS_WITH': 'cw',
 'COMPLICATES': 'cp',
 'CONVERTS_TO': 'ct',
 'DIAGNOSES': 'dg',
 'DISRUPTS': 'ds',
 'INHIBITS': 'in',
 'INTERACTS_WITH': 'iw',
 'ISA': 'i',
 'LOCATION_OF': 'lo',
 'MANIFESTATION_OF': 'mfo',
 'METHOD_OF': 'mo',
 'OCCURS_IN': 'oi',
 'PART_OF': 'po',
 'PRECEDES': 'pc',
 'PREDISPOSES': 'ps',
 'PREP': 'pr',
 'PREVENTS': 'pv',
 'PROCESS_OF': 'pro',
 'PRODUCES': 'pd',
 'STIMULATES': 'st',
 'TREATS': 't',
 'USES': 'u',
 'compared_with': 'cpw',
 'different_from': 'df',
 'different_than': 'dt',
 'higher_than': 'ht',
 'lower_than': 'lt',
 'same_as': 'sa'}
abv_pred = {v:k for k,v in pred_abr.items()}

In [34]:
abv = pd.DataFrame(list(pred_abr.items()) + list(type_abv.items()), columns=['full_name', 'abv'])
abv.to_csv("abv.csv", index=None)
abv.head()

     full_name  abv
0     INHIBITS   in
1      AFFECTS   af
2  LOCATION_OF   lo
3    METHOD_OF   mo
4   PROCESS_OF  pro